<?php
require_once 'includes/header.php';require_once 'includes/navbar.php';
$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $username=trim($_POST['username']??'');$first=trim($_POST['first_name']??'');$last=trim($_POST['last_name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$password=$_POST['password']??'';$confirm=$_POST['confirm_password']??'';$gender=$_POST['gender']??'Other';$dob=$_POST['date_of_birth']??null;$address=trim($_POST['address']??'');$city=trim($_POST['city']??'');$country=trim($_POST['country']??'');$postal=trim($_POST['postal_code']??'');$role='customer';
 if(strlen($username)<3){$error='Username must be at least 3 characters.';}elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)){$error='Please enter a valid email address.';}elseif(strlen($password)<8){$error='Password must contain at least 8 characters.';}elseif($password!==$confirm){$error='Passwords do not match.';}else{
  $check=mysqli_prepare($conn,'SELECT user_id,username,email,phone FROM users WHERE username=? OR email=? OR phone=? LIMIT 1');mysqli_stmt_bind_param($check,'sss',$username,$email,$phone);mysqli_stmt_execute($check);$existing=mysqli_fetch_assoc(mysqli_stmt_get_result($check));
  if($existing){$error=$existing['username']===$username?'That username is already taken.':($existing['email']===$email?'That email is already registered.':'That phone number is already registered.');}
  else{$full=trim($first.' '.$last);$hash=password_hash($password,PASSWORD_DEFAULT);mysqli_begin_transaction($conn);try{$stmt=mysqli_prepare($conn,"INSERT INTO users (username,full_name,first_name,last_name,email,phone,password,role,gender,date_of_birth,address,city,country,postal_code,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'active')");mysqli_stmt_bind_param($stmt,'ssssssssssssss',$username,$full,$first,$last,$email,$phone,$hash,$role,$gender,$dob,$address,$city,$country,$postal);if(!mysqli_stmt_execute($stmt))throw new Exception(mysqli_error($conn));$uid=mysqli_insert_id($conn);mysqli_commit($conn);$success='Account created successfully. You can sign in now.';$_POST=[];}catch(Throwable $e){mysqli_rollback($conn);$error='Registration could not be completed. Please try again.';}}
 }
}
function old($key,$default=''){return htmlspecialchars($_POST[$key]??$default);}
?>
<section class="auth-shell"><div class="auth-card register-card">
<aside class="auth-side"><div><div class="hbs-eyebrow mb-4"><i class="fa-solid fa-user-plus"></i> Create your account</div><h2>Create your guest account and start booking.</h2><p>Public registration creates a guest account only. Hotel owner accounts are created and managed separately by the website administrator.</p></div><div class="auth-points"><div class="auth-point"><i class="fa-solid fa-bed"></i><span>Guest booking and reservation history</span></div><div class="auth-point"><i class="fa-solid fa-user-shield"></i><span>Owner and admin accounts are managed separately</span></div><div class="auth-point"><i class="fa-solid fa-lock"></i><span>Secure bcrypt password storage</span></div></div></aside>
<div class="auth-form"><span class="text-primary fw-bold small">REGISTER</span><h1 class="mt-1">Create a StayFlow account</h1><p class="text-muted small mb-4">Enter your profile details. You can update them later.</p><?php if($error):?><div class="alert alert-danger py-2 small"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success py-2 small"><?=htmlspecialchars($success)?> <a href="login.php" class="fw-bold">Sign in</a></div><?php endif;?>
<form method="POST" action="register.php"><div class="register-form-grid"><div><label class="form-label">First name</label><input class="form-control" name="first_name" required value="<?=old('first_name')?>"></div><div><label class="form-label">Last name</label><input class="form-control" name="last_name" required value="<?=old('last_name')?>"></div><div><label class="form-label">Username</label><input class="form-control" name="username" minlength="3" required value="<?=old('username')?>"></div><div><label class="form-label">Email</label><input class="form-control" type="email" name="email" required value="<?=old('email')?>"></div><div><label class="form-label">Phone</label><input class="form-control" name="phone" required value="<?=old('phone')?>"></div><div><label class="form-label">Date of birth</label><input class="form-control" type="date" name="date_of_birth" required value="<?=old('date_of_birth')?>"></div><div><label class="form-label">Gender</label><select class="form-select" name="gender"><?php foreach(['Male','Female','Other'] as $g):?><option value="<?=$g?>" <?=old('gender')===$g?'selected':''?>><?=$g?></option><?php endforeach;?></select></div><div><label class="form-label">City</label><input class="form-control" name="city" required value="<?=old('city')?>"></div><div><label class="form-label">Country</label><input class="form-control" name="country" required value="<?=old('country','Myanmar')?>"></div><div><label class="form-label">Postal code</label><input class="form-control" name="postal_code" value="<?=old('postal_code')?>"></div><div class="span-2"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2" required><?=old('address')?></textarea></div><div><label class="form-label">Password</label><input class="form-control" type="password" name="password" minlength="8" required></div><div><label class="form-label">Confirm password</label><input class="form-control" type="password" name="confirm_password" minlength="8" required></div><div class="span-2"><button class="btn btn-primary w-100 fw-bold" type="submit">Create account <i class="fa-solid fa-arrow-right ms-1"></i></button></div></div></form><p class="auth-note text-center mt-3 mb-0">Already registered? <a href="login.php" class="fw-bold text-decoration-none">Sign in</a></p></div>
</div></section><?php require_once 'includes/footer.php';?>
